// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg8tGwYppfgVPxPol2lkg2FtEKCcUYX3k',
    appId: '1:151385656356:web:5f408ebd2ea0998e875cb1',
    messagingSenderId: '151385656356',
    projectId: 'kusortir',
    authDomain: 'kusortir.firebaseapp.com',
    storageBucket: 'kusortir.firebasestorage.app',
    measurementId: 'G-05VSNDMNRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwJJcoeaA0Ze7E5O3QzGcJ2a0frSn2OZY',
    appId: '1:151385656356:android:8f3628ded261787d875cb1',
    messagingSenderId: '151385656356',
    projectId: 'kusortir',
    storageBucket: 'kusortir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcgnnNRoYa6ySmCbHFPza-fB96HURrBcA',
    appId: '1:151385656356:ios:314b04a048cf1a5b875cb1',
    messagingSenderId: '151385656356',
    projectId: 'kusortir',
    storageBucket: 'kusortir.firebasestorage.app',
    iosBundleId: 'com.example.kusortir',
  );
}
